server:
  port: 8082
  servlet:
    context-path: /show
    
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
#自定义参数
cat: tom
mouse: jack
animal: "cat: ${cat} , mouse: ${mouse}"
girl:
    cupSize: B
    height: 169
    