spring:
  profiles:
    active:
    - dev
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.163.com
    username: zhangxianglink@163.com
    password: shouquan163
    default-encoding: UTF-8