server:
  port: 8089
  servlet:
    context-path: /show
    
spring:
  datasource: 
  #本机没有blog数据库
    url: jdbc:mysql://127.0.0.1:3306/school
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    
#自定义参数
cat: tom
mouse: jack
animal: "cat: ${cat} , mouse: ${mouse}"
girl:
    cupSize: B
    height: 169
    